theme = "tsmanner"

[editor]
true-color = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "underline"

[editor.statusline]
right = ["diagnostics", "selections", "primary-selection-length", "register", "position", "file-encoding"]
